// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkgiRpY5edwOwxVizbLIfB2QpNOaxsl8c',
    appId: '1:537378189849:web:47cc10bf788e47856db088',
    messagingSenderId: '537378189849',
    projectId: 'reddit-master-9b37e',
    authDomain: 'reddit-master-9b37e.firebaseapp.com',
    storageBucket: 'reddit-master-9b37e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkctBYaZUmv_lCH86w96Nhm8AtPRID-L0',
    appId: '1:537378189849:android:1c6d58271c45f5216db088',
    messagingSenderId: '537378189849',
    projectId: 'reddit-master-9b37e',
    storageBucket: 'reddit-master-9b37e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoUCldBk0uvapVNVVm3_hGmmGfpc1ost0',
    appId: '1:537378189849:ios:5040572ad6aa6da96db088',
    messagingSenderId: '537378189849',
    projectId: 'reddit-master-9b37e',
    storageBucket: 'reddit-master-9b37e.appspot.com',
    iosBundleId: 'com.example.redditCloneApplication',
  );
}
